"""create disputes table

Revision ID: 270180dcb20b
Revises: 83a433d2c5fe
Create Date: 2026-08-15 20:30:31.106495

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '270180dcb20b'
down_revision: Union[str, Sequence[str], None] = '83a433d2c5fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('disputes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('filed_by_user_id', sa.UUID(), nullable=False),
    sa.Column('reason', sa.Enum('damaged', 'missing', 'cod_mismatch', 'other', name='disputereason'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('open', 'resolved', name='disputestatus'), nullable=False),
    sa.Column('resolution_type', sa.Enum('full_refund', 'partial_refund', 'wallet_adjustment', 'claim_denied', name='resolutiontype'), nullable=True),
    sa.Column('resolved_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('reviewer_notes', sa.Text(), nullable=True),
    sa.Column('order_status_before_dispute', postgresql.ENUM('pending', 'assigned', 'picked_up', 'delivered', 'dropped_at_terminal', 'delivery_failed', 'disputed', 'cancelled', 'cancelled_post_pickup', 'returned', name='orderstatus',create_type=False), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['filed_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('disputes')
    # ### end Alembic commands ###
