"""create orders and order_tracking_logs

Revision ID: b1e9ac6582c9
Revises: bfb5e831af17
Create Date: 2026-08-11 21:11:37.866843

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b1e9ac6582c9'
down_revision: Union[str, Sequence[str], None] = 'bfb5e831af17'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('sender_id', sa.UUID(), nullable=False),
    sa.Column('rider_id', sa.UUID(), nullable=True),
    sa.Column('delivery_mode', sa.Enum('door_to_door', 'bus_terminal', name='deliverymode'), nullable=False),
    sa.Column('recipient_name', sa.String(), nullable=False),
    sa.Column('recipient_phone', sa.String(), nullable=False),
    sa.Column('pickup_address', sa.String(), nullable=False),
    sa.Column('pickup_lat', sa.Float(), nullable=False),
    sa.Column('pickup_lng', sa.Float(), nullable=False),
    sa.Column('dropoff_address', sa.String(), nullable=True),
    sa.Column('dropoff_lat', sa.Float(), nullable=True),
    sa.Column('dropoff_lng', sa.Float(), nullable=True),
    sa.Column('terminal_name', sa.String(), nullable=True),
    sa.Column('bus_line', sa.String(), nullable=True),
    sa.Column('item_size', sa.String(), nullable=False),
    sa.Column('item_value', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('cod_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('delivery_fee', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('fee_payer', sa.Enum('sender', 'recipient', name='feepayer'), nullable=False),
    sa.Column('status', sa.Enum('pending', 'assigned', 'picked_up', 'delivered', 'dropped_at_terminal', 'delivery_failed', 'disputed', 'cancelled', 'cancelled_post_pickup', 'returned', name='orderstatus'), nullable=False),
    sa.Column('terms_accepted', sa.Boolean(), nullable=False),
    sa.Column('cancel_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['rider_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('order_tracking_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'assigned', 'picked_up', 'delivered', 'dropped_at_terminal', 'delivery_failed', 'disputed', 'cancelled', 'cancelled_post_pickup', 'returned', name='orderstatus'), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order_tracking_logs')
    op.drop_table('orders')
    # ### end Alembic commands ###
